GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA shopping TO shopping;

ALTER DEFAULT PRIVILEGES FOR ROLE shopping_owner IN SCHEMA shopping
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO shopping;
